# Generated by Django 2.1 on 2018-08-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portoflio_site',
            new_name='portfolio_site',
        ),
    ]
